### ISSUE TITLE
想请问一下怎么用Prismjs设置代码高亮quq

### ISSUE THREAD

**Issue by InariInDream** [TransparentLC/hexo-theme-akarin#1]
照着官方文档把config里设置成这样了
![image](https://user-images.githubusercontent.com/101713235/165472842-25f59c62-0f1c-4db4-a2de-488ebfb62a43.png)
然后在theme下的config设置如下
![image](https://user-images.githubusercontent.com/101713235/165473411-ac3b7bc0-4697-4a83-a1cd-758a2f32261b.png)
但是自己Blog里面的代码还是没有行号和高亮quq
![image](https://user-images.githubusercontent.com/101713235/165476605-9de016c7-a88c-4d30-a8b6-1d190d37bc06.png)
![image](https://user-images.githubusercontent.com/101713235/165476787-c31c0add-5463-4fdc-ab51-2fd575a9e85c.png)

前端小白 调了快一下午还没调好（

**Comment by TransparentLC** [comment]
如果设置了 `prismjs.enable = true` 和 `prismjs.preprocess = true` 的话 Hexo 在生成网页的时候就会调用 Prism 添加代码高亮了（参见[这里](https://hexo.io/zh-cn/docs/syntax-highlight.html#PrismJS)，查看网页源代码可以看到原文的代码部分会有很多 `<span class="token ...">`），Prism 的那几个文件不需要在 `scripts` 里添加，否则用浏览器打开的时候再添加一遍高亮（？）反而会把高亮去掉。

**Comment by InariInDream** [comment]
好像对了 是我自作聪明了（
